### PR TITLE
Update pekko-sbt-paradox (#161)

### PR DESCRIPTION
**Pull request by mdedetrich**
(cherry picked from commit 31e1952304d72049f85824937d361483e721a971)

### CODE REVIEW

**Review by He-Pin — APPROVED** [review]
lgtm

**Comment by He-Pin** [comment]
1.
```
[error] sbt.librarymanagement.ResolveException: Error downloading org.apache.pekko:pekko-theme-paradox:1.0.1-RC1+5-13892678-SNAPSHOT
[error]   Not found
[error]   Not found
[error]   not found: /home/runner/.ivy2/localorg.apache.pekko/pekko-theme-paradox/1.0.1-RC1+5-13892678-SNAPSHOT/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/org/apache/pekko/pekko-theme-paradox/1.0.1-RC1+5-13892678-SNAPSHOT/pekko-theme-paradox-1.0.1-RC1+5-13892678-SNAPSHOT.pom
```

2.

**Comment by mdedetrich** [comment]
> ```
> [error] sbt.librarymanagement.ResolveException: Error downloading org.apache.pekko:pekko-theme-paradox:1.0.1-RC1+5-13892678-SNAPSHOT
> [error]   Not found
> [error]   Not found
> [error]   not found: /home/runner/.ivy2/localorg.apache.pekko/pekko-theme-paradox/1.0.1-RC1+5-13892678-SNAPSHOT/ivys/ivy.xml
> [error]   not found: https://repo1.maven.org/maven2/org/apache/pekko/pekko-theme-paradox/1.0.1-RC1+5-13892678-SNAPSHOT/pekko-theme-paradox-1.0.1-RC1+5-13892678-SNAPSHOT.pom
> ```

Yes this happens because the snapshots repo is being overloaded. A release is on the way but its still waiting for another binding one vote (see https://lists.apache.org/thread/dpqckc5g23fw7q6plh0d89md7tn6rr1c)

**Comment by mdedetrich** [comment]
Hmm wait, I think its because this repo doesn't have snapshots repository which wasn't cherry picked, fixing

**Pull request merged**
