### PR TITLE
Use Pekko in conf and cql documentation

### PR DESCRIPTION
**Pull request by mdedetrich**
Self explanatory. @nvollmar since you update the cql queries/config make sure to double check so that it matches with the code.

### CODE REVIEW

**Comment by pjfanning** [comment]
This PR conflicts with an existing PR - #36

**Comment by pjfanning** [comment]
This PR has some extra stuff - relating to the pekko keyspace. My PR has some other stuff that's not in this one.

**Comment by mdedetrich** [comment]
> This PR has some extra stuff - relating to the pekko keyspace. My PR has some other stuff that's not in this one.

Cool, I will rebase this PR when yours is merged

**Review by nvollmar — APPROVED** [review]
lgtm - apart from the overlaps with the other PR

**Pull request merged**
