### PR TITLE
Publish nightly docs

### PR DESCRIPTION
**Pull request by mdedetrich**
Taken from pekko-management which is published https://github.com/apache/incubator-pekko-management/blob/main/.github/workflows/publish-nightly.yml#L40-L61

### CODE REVIEW

**Review by danischroeter — APPROVED** [review]
lgtm

**Comment by pjfanning** [comment]
I'd prefer not to start publishing docs until we fix up the Akka and Alpakkka refs and links.

**Comment by mdedetrich** [comment]
> I'd prefer not to start publishing docs until we fix up the Akka and Alpakkka refs and links.

Okay sure, people were asking for the docs which is why I made the PR but its not urgent

**Review by pjfanning — APPROVED** [review]
lgtm

**Comment by pjfanning** [comment]
@mdedetrich with https://github.com/apache/incubator-pekko-persistence-cassandra/pull/49 merged, we are in a better position to merge this

**Pull request merged**
